# Generated by Django 3.1.2 on 2020-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200, null=True)),
                ('setting_value', models.CharField(max_length=100, null=True)),
                ('setting_description', models.TextField(default='null', null=True)),
            ],
        ),
    ]
