# Generated by Django 3.1.2 on 2020-12-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(max_length=200, null=True)),
                ('prod_description', models.TextField(max_length=200, null=True)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('prod_category', models.TextField(default='null', null=True)),
            ],
        ),
    ]
