# Generated by Django 3.1.2 on 2020-12-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_description',
            field=models.TextField(default='null', null=True),
        ),
    ]
