# Generated by Django 3.1.2 on 2020-12-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201209_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.CharField(choices=[('category 1', 'A'), ('category 2', 'B'), ('category 3', 'C'), ('category 4', 'D'), ('category 5', 'E')], max_length=200),
        ),
    ]
