# Generated by Django 3.1.2 on 2020-12-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201209_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.CharField(choices=[('category 1', 'category 1'), ('category 2', 'category 2'), ('category 3', 'category 3'), ('category 4', 'category 4'), ('category 5', 'category 5')], max_length=100),
        ),
    ]
