# Generated by Django 3.1.2 on 2020-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_prod_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_instructions',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
