# Generated by Django 3.1.2 on 2020-12-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201211_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_instructions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
