# Generated by Django 3.1.2 on 2020-12-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201211_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_instructions',
        ),
    ]
